version: '2'
services:
  app:
    build: .
    restart: always
    volumes:
      - ./www:/var/www/html
    volumes_from:
      - volumes_data
      
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    links:
      - app
    volumes_from:
      - app
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - PHP_UPLOAD_MAX_FILESIZE=100M
    restart: always
    ports:
      - 33060:80
    volumes_from:
      - volumes_data
    links:
      - database

  database:
    image: mariadb:latest
    restart: always
    volumes_from:
      - volumes_data
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"

  volumes_data:
    image: tianon/true
    volumes:
      - ./store/sessions:/sessions
      - ./store/database:/var/lib/mysql
      